// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: natchain/wallet/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSetSafetyLimit struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SafetyLimit int64  `protobuf:"varint,2,opt,name=safety_limit,json=safetyLimit,proto3" json:"safety_limit,omitempty"`
}

func (m *MsgSetSafetyLimit) Reset()         { *m = MsgSetSafetyLimit{} }
func (m *MsgSetSafetyLimit) String() string { return proto.CompactTextString(m) }
func (*MsgSetSafetyLimit) ProtoMessage()    {}
func (*MsgSetSafetyLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{0}
}
func (m *MsgSetSafetyLimit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetSafetyLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetSafetyLimit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetSafetyLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetSafetyLimit.Merge(m, src)
}
func (m *MsgSetSafetyLimit) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetSafetyLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetSafetyLimit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetSafetyLimit proto.InternalMessageInfo

func (m *MsgSetSafetyLimit) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetSafetyLimit) GetSafetyLimit() int64 {
	if m != nil {
		return m.SafetyLimit
	}
	return 0
}

type MsgSetSafetyLimitResponse struct {
}

func (m *MsgSetSafetyLimitResponse) Reset()         { *m = MsgSetSafetyLimitResponse{} }
func (m *MsgSetSafetyLimitResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetSafetyLimitResponse) ProtoMessage()    {}
func (*MsgSetSafetyLimitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{1}
}
func (m *MsgSetSafetyLimitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetSafetyLimitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetSafetyLimitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetSafetyLimitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetSafetyLimitResponse.Merge(m, src)
}
func (m *MsgSetSafetyLimitResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetSafetyLimitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetSafetyLimitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetSafetyLimitResponse proto.InternalMessageInfo

type MsgSetColdAddress struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ColdAddress string `protobuf:"bytes,2,opt,name=cold_address,json=coldAddress,proto3" json:"cold_address,omitempty"`
}

func (m *MsgSetColdAddress) Reset()         { *m = MsgSetColdAddress{} }
func (m *MsgSetColdAddress) String() string { return proto.CompactTextString(m) }
func (*MsgSetColdAddress) ProtoMessage()    {}
func (*MsgSetColdAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{2}
}
func (m *MsgSetColdAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetColdAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetColdAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetColdAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetColdAddress.Merge(m, src)
}
func (m *MsgSetColdAddress) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetColdAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetColdAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetColdAddress proto.InternalMessageInfo

func (m *MsgSetColdAddress) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetColdAddress) GetColdAddress() string {
	if m != nil {
		return m.ColdAddress
	}
	return ""
}

type MsgSetColdAddressResponse struct {
}

func (m *MsgSetColdAddressResponse) Reset()         { *m = MsgSetColdAddressResponse{} }
func (m *MsgSetColdAddressResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetColdAddressResponse) ProtoMessage()    {}
func (*MsgSetColdAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{3}
}
func (m *MsgSetColdAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetColdAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetColdAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetColdAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetColdAddressResponse.Merge(m, src)
}
func (m *MsgSetColdAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetColdAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetColdAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetColdAddressResponse proto.InternalMessageInfo

type MsgSetAutoTransfer struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Threshold int64  `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Amount    string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Enabled   bool   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (m *MsgSetAutoTransfer) Reset()         { *m = MsgSetAutoTransfer{} }
func (m *MsgSetAutoTransfer) String() string { return proto.CompactTextString(m) }
func (*MsgSetAutoTransfer) ProtoMessage()    {}
func (*MsgSetAutoTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{4}
}
func (m *MsgSetAutoTransfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetAutoTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetAutoTransfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetAutoTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetAutoTransfer.Merge(m, src)
}
func (m *MsgSetAutoTransfer) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetAutoTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetAutoTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetAutoTransfer proto.InternalMessageInfo

func (m *MsgSetAutoTransfer) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetAutoTransfer) GetThreshold() int64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *MsgSetAutoTransfer) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgSetAutoTransfer) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type MsgSetAutoTransferResponse struct {
}

func (m *MsgSetAutoTransferResponse) Reset()         { *m = MsgSetAutoTransferResponse{} }
func (m *MsgSetAutoTransferResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetAutoTransferResponse) ProtoMessage()    {}
func (*MsgSetAutoTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{5}
}
func (m *MsgSetAutoTransferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetAutoTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetAutoTransferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetAutoTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetAutoTransferResponse.Merge(m, src)
}
func (m *MsgSetAutoTransferResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetAutoTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetAutoTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetAutoTransferResponse proto.InternalMessageInfo

type MsgAddPartner struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Memo    string `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *MsgAddPartner) Reset()         { *m = MsgAddPartner{} }
func (m *MsgAddPartner) String() string { return proto.CompactTextString(m) }
func (*MsgAddPartner) ProtoMessage()    {}
func (*MsgAddPartner) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{6}
}
func (m *MsgAddPartner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddPartner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddPartner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddPartner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddPartner.Merge(m, src)
}
func (m *MsgAddPartner) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddPartner) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddPartner.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddPartner proto.InternalMessageInfo

func (m *MsgAddPartner) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddPartner) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgAddPartner) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgAddPartner) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type MsgAddPartnerResponse struct {
}

func (m *MsgAddPartnerResponse) Reset()         { *m = MsgAddPartnerResponse{} }
func (m *MsgAddPartnerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddPartnerResponse) ProtoMessage()    {}
func (*MsgAddPartnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{7}
}
func (m *MsgAddPartnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddPartnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddPartnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddPartnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddPartnerResponse.Merge(m, src)
}
func (m *MsgAddPartnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddPartnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddPartnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddPartnerResponse proto.InternalMessageInfo

type MsgRemovePartner struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *MsgRemovePartner) Reset()         { *m = MsgRemovePartner{} }
func (m *MsgRemovePartner) String() string { return proto.CompactTextString(m) }
func (*MsgRemovePartner) ProtoMessage()    {}
func (*MsgRemovePartner) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{8}
}
func (m *MsgRemovePartner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemovePartner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemovePartner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemovePartner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemovePartner.Merge(m, src)
}
func (m *MsgRemovePartner) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemovePartner) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemovePartner.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemovePartner proto.InternalMessageInfo

func (m *MsgRemovePartner) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRemovePartner) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type MsgRemovePartnerResponse struct {
}

func (m *MsgRemovePartnerResponse) Reset()         { *m = MsgRemovePartnerResponse{} }
func (m *MsgRemovePartnerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemovePartnerResponse) ProtoMessage()    {}
func (*MsgRemovePartnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{9}
}
func (m *MsgRemovePartnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemovePartnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemovePartnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemovePartnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemovePartnerResponse.Merge(m, src)
}
func (m *MsgRemovePartnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemovePartnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemovePartnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemovePartnerResponse proto.InternalMessageInfo

type MsgUpdatePartner struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Memo    string `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *MsgUpdatePartner) Reset()         { *m = MsgUpdatePartner{} }
func (m *MsgUpdatePartner) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePartner) ProtoMessage()    {}
func (*MsgUpdatePartner) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{10}
}
func (m *MsgUpdatePartner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePartner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePartner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePartner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePartner.Merge(m, src)
}
func (m *MsgUpdatePartner) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePartner) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePartner.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePartner proto.InternalMessageInfo

func (m *MsgUpdatePartner) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdatePartner) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgUpdatePartner) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgUpdatePartner) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type MsgUpdatePartnerResponse struct {
}

func (m *MsgUpdatePartnerResponse) Reset()         { *m = MsgUpdatePartnerResponse{} }
func (m *MsgUpdatePartnerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePartnerResponse) ProtoMessage()    {}
func (*MsgUpdatePartnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd67dd532c52bb, []int{11}
}
func (m *MsgUpdatePartnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePartnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePartnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePartnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePartnerResponse.Merge(m, src)
}
func (m *MsgUpdatePartnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePartnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePartnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePartnerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetSafetyLimit)(nil), "natchain.wallet.v1.MsgSetSafetyLimit")
	proto.RegisterType((*MsgSetSafetyLimitResponse)(nil), "natchain.wallet.v1.MsgSetSafetyLimitResponse")
	proto.RegisterType((*MsgSetColdAddress)(nil), "natchain.wallet.v1.MsgSetColdAddress")
	proto.RegisterType((*MsgSetColdAddressResponse)(nil), "natchain.wallet.v1.MsgSetColdAddressResponse")
	proto.RegisterType((*MsgSetAutoTransfer)(nil), "natchain.wallet.v1.MsgSetAutoTransfer")
	proto.RegisterType((*MsgSetAutoTransferResponse)(nil), "natchain.wallet.v1.MsgSetAutoTransferResponse")
	proto.RegisterType((*MsgAddPartner)(nil), "natchain.wallet.v1.MsgAddPartner")
	proto.RegisterType((*MsgAddPartnerResponse)(nil), "natchain.wallet.v1.MsgAddPartnerResponse")
	proto.RegisterType((*MsgRemovePartner)(nil), "natchain.wallet.v1.MsgRemovePartner")
	proto.RegisterType((*MsgRemovePartnerResponse)(nil), "natchain.wallet.v1.MsgRemovePartnerResponse")
	proto.RegisterType((*MsgUpdatePartner)(nil), "natchain.wallet.v1.MsgUpdatePartner")
	proto.RegisterType((*MsgUpdatePartnerResponse)(nil), "natchain.wallet.v1.MsgUpdatePartnerResponse")
}

func init() { proto.RegisterFile("natchain/wallet/v1/tx.proto", fileDescriptor_30bd67dd532c52bb) }

var fileDescriptor_30bd67dd532c52bb = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe3, 0x26, 0x14, 0x32, 0x6d, 0xf9, 0x58, 0x09, 0x62, 0xdc, 0xca, 0x4a, 0x2b, 0x40,
	0xa1, 0x02, 0x47, 0x81, 0x1b, 0xb7, 0xc0, 0x95, 0x48, 0xc8, 0x2d, 0x97, 0x1e, 0xa8, 0xb6, 0xde,
	0x8d, 0x13, 0xc9, 0xeb, 0x8d, 0xbc, 0xdb, 0xd0, 0x48, 0x1c, 0x10, 0x67, 0x0e, 0x3c, 0x4a, 0x1f,
	0x83, 0x63, 0x8f, 0x1c, 0x51, 0x72, 0xe8, 0x89, 0x77, 0x40, 0xb1, 0xb3, 0xfe, 0x4a, 0xed, 0x44,
	0xea, 0x6d, 0x27, 0xfb, 0x9f, 0xf9, 0xfd, 0x33, 0x9a, 0xf1, 0xc2, 0xae, 0x8f, 0xa5, 0x33, 0xc0,
	0x43, 0xbf, 0xfd, 0x15, 0x7b, 0x1e, 0x95, 0xed, 0x71, 0xa7, 0x2d, 0x2f, 0xac, 0x51, 0xc0, 0x25,
	0x47, 0x48, 0x5d, 0x5a, 0xd1, 0xa5, 0x35, 0xee, 0x18, 0x0d, 0x87, 0x0b, 0xc6, 0x45, 0x9b, 0x09,
	0x77, 0xae, 0x65, 0xc2, 0x8d, 0xc4, 0x07, 0x5f, 0xe0, 0x51, 0x4f, 0xb8, 0x47, 0x54, 0x1e, 0xe1,
	0x3e, 0x95, 0x93, 0x8f, 0x43, 0x36, 0x94, 0x48, 0x87, 0xbb, 0x4e, 0x40, 0xb1, 0xe4, 0x81, 0xae,
	0x35, 0xb5, 0x56, 0xdd, 0x56, 0x21, 0xda, 0x87, 0x6d, 0x11, 0x0a, 0x4f, 0xbd, 0xb9, 0x52, 0xdf,
	0x68, 0x6a, 0xad, 0xaa, 0xbd, 0x25, 0x92, 0xe4, 0x77, 0xdb, 0x3f, 0xae, 0x2f, 0x0f, 0x55, 0xc2,
	0xc1, 0x2e, 0x3c, 0x5d, 0xaa, 0x6f, 0x53, 0x31, 0xe2, 0xbe, 0xa0, 0x09, 0xfc, 0x03, 0xf7, 0x48,
	0x97, 0x90, 0x80, 0x0a, 0x51, 0x0e, 0x77, 0xb8, 0x47, 0x4e, 0x71, 0xa4, 0x0c, 0xe1, 0x75, 0x7b,
	0xcb, 0x49, 0x92, 0x8b, 0xe0, 0xa9, 0xfa, 0x31, 0xfc, 0xa7, 0x06, 0x28, 0xba, 0xed, 0x9e, 0x4b,
	0x7e, 0x1c, 0x60, 0x5f, 0xf4, 0x69, 0x50, 0x82, 0xdf, 0x83, 0xba, 0x1c, 0x04, 0x54, 0x0c, 0xb8,
	0x47, 0x16, 0x7f, 0x3c, 0xf9, 0x01, 0x3d, 0x81, 0x4d, 0xcc, 0xf8, 0xb9, 0x2f, 0xf5, 0x6a, 0x98,
	0xb6, 0x88, 0xe6, 0xf5, 0xa8, 0x8f, 0xcf, 0x3c, 0x4a, 0xf4, 0x5a, 0x53, 0x6b, 0xdd, 0xb3, 0x55,
	0x98, 0xf3, 0xba, 0x07, 0xc6, 0xb2, 0x9b, 0xd8, 0xec, 0x04, 0x76, 0x7a, 0xc2, 0xed, 0x12, 0xf2,
	0x09, 0x07, 0xd2, 0x2f, 0xb5, 0x89, 0xa0, 0xe6, 0x63, 0x46, 0x17, 0xdd, 0x09, 0xcf, 0x73, 0xb5,
	0x6a, 0x5a, 0xe4, 0x4e, 0x85, 0x73, 0x35, 0xa3, 0x8c, 0x87, 0xde, 0xea, 0x76, 0x78, 0xce, 0x19,
	0x6b, 0xc0, 0xe3, 0x0c, 0x3a, 0xf6, 0x74, 0x0c, 0x0f, 0x7b, 0xc2, 0xb5, 0x29, 0xe3, 0x63, 0xba,
	0xda, 0x56, 0xca, 0xc2, 0x46, 0xc6, 0x42, 0x0e, 0x67, 0x80, 0x9e, 0xaf, 0x1a, 0x13, 0xbf, 0x85,
	0xc4, 0xcf, 0x23, 0x82, 0xe5, 0x6d, 0x88, 0x71, 0x8b, 0xaa, 0xa9, 0x16, 0xad, 0x6e, 0x44, 0xe4,
	0x2c, 0x43, 0x57, 0xce, 0xde, 0xfc, 0xab, 0x41, 0xb5, 0x27, 0x5c, 0xd4, 0x87, 0xfb, 0xb9, 0x5d,
	0x7a, 0x6e, 0x2d, 0xaf, 0xa3, 0xb5, 0xb4, 0x12, 0xc6, 0xeb, 0xb5, 0x64, 0x8a, 0xb7, 0xe0, 0xa4,
	0xd7, 0xa6, 0x84, 0x93, 0x92, 0x95, 0x71, 0x6e, 0x58, 0x12, 0x34, 0x84, 0x07, 0xf9, 0x05, 0x79,
	0x51, 0x5c, 0x21, 0xad, 0x33, 0xac, 0xf5, 0x74, 0x31, 0xea, 0x04, 0x20, 0x35, 0xdf, 0xfb, 0x05,
	0xd9, 0x89, 0xc4, 0x78, 0xb9, 0x52, 0x12, 0xd7, 0x76, 0x60, 0x27, 0x3b, 0xa7, 0xcf, 0x0a, 0x72,
	0x33, 0x2a, 0xe3, 0xd5, 0x3a, 0xaa, 0x34, 0x24, 0x3b, 0x9a, 0x45, 0x90, 0x8c, 0xaa, 0x10, 0x72,
	0xe3, 0xa0, 0x19, 0x77, 0xbe, 0x5f, 0x5f, 0x1e, 0x6a, 0xef, 0x3b, 0xbf, 0xa7, 0xa6, 0x76, 0x35,
	0x35, 0xb5, 0xbf, 0x53, 0x53, 0xfb, 0x35, 0x33, 0x2b, 0x57, 0x33, 0xb3, 0xf2, 0x67, 0x66, 0x56,
	0x4e, 0x1a, 0xf1, 0xd3, 0x70, 0xa1, 0x1e, 0x07, 0x39, 0x19, 0x51, 0x71, 0xb6, 0x19, 0x7e, 0xf0,
	0xdf, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x83, 0xdc, 0x83, 0xe5, 0x3c, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SetSafetyLimit(ctx context.Context, in *MsgSetSafetyLimit, opts ...grpc.CallOption) (*MsgSetSafetyLimitResponse, error)
	SetColdAddress(ctx context.Context, in *MsgSetColdAddress, opts ...grpc.CallOption) (*MsgSetColdAddressResponse, error)
	SetAutoTransfer(ctx context.Context, in *MsgSetAutoTransfer, opts ...grpc.CallOption) (*MsgSetAutoTransferResponse, error)
	AddPartner(ctx context.Context, in *MsgAddPartner, opts ...grpc.CallOption) (*MsgAddPartnerResponse, error)
	RemovePartner(ctx context.Context, in *MsgRemovePartner, opts ...grpc.CallOption) (*MsgRemovePartnerResponse, error)
	UpdatePartner(ctx context.Context, in *MsgUpdatePartner, opts ...grpc.CallOption) (*MsgUpdatePartnerResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetSafetyLimit(ctx context.Context, in *MsgSetSafetyLimit, opts ...grpc.CallOption) (*MsgSetSafetyLimitResponse, error) {
	out := new(MsgSetSafetyLimitResponse)
	err := c.cc.Invoke(ctx, "/natchain.wallet.v1.Msg/SetSafetyLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetColdAddress(ctx context.Context, in *MsgSetColdAddress, opts ...grpc.CallOption) (*MsgSetColdAddressResponse, error) {
	out := new(MsgSetColdAddressResponse)
	err := c.cc.Invoke(ctx, "/natchain.wallet.v1.Msg/SetColdAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetAutoTransfer(ctx context.Context, in *MsgSetAutoTransfer, opts ...grpc.CallOption) (*MsgSetAutoTransferResponse, error) {
	out := new(MsgSetAutoTransferResponse)
	err := c.cc.Invoke(ctx, "/natchain.wallet.v1.Msg/SetAutoTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddPartner(ctx context.Context, in *MsgAddPartner, opts ...grpc.CallOption) (*MsgAddPartnerResponse, error) {
	out := new(MsgAddPartnerResponse)
	err := c.cc.Invoke(ctx, "/natchain.wallet.v1.Msg/AddPartner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemovePartner(ctx context.Context, in *MsgRemovePartner, opts ...grpc.CallOption) (*MsgRemovePartnerResponse, error) {
	out := new(MsgRemovePartnerResponse)
	err := c.cc.Invoke(ctx, "/natchain.wallet.v1.Msg/RemovePartner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdatePartner(ctx context.Context, in *MsgUpdatePartner, opts ...grpc.CallOption) (*MsgUpdatePartnerResponse, error) {
	out := new(MsgUpdatePartnerResponse)
	err := c.cc.Invoke(ctx, "/natchain.wallet.v1.Msg/UpdatePartner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SetSafetyLimit(context.Context, *MsgSetSafetyLimit) (*MsgSetSafetyLimitResponse, error)
	SetColdAddress(context.Context, *MsgSetColdAddress) (*MsgSetColdAddressResponse, error)
	SetAutoTransfer(context.Context, *MsgSetAutoTransfer) (*MsgSetAutoTransferResponse, error)
	AddPartner(context.Context, *MsgAddPartner) (*MsgAddPartnerResponse, error)
	RemovePartner(context.Context, *MsgRemovePartner) (*MsgRemovePartnerResponse, error)
	UpdatePartner(context.Context, *MsgUpdatePartner) (*MsgUpdatePartnerResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetSafetyLimit(ctx context.Context, req *MsgSetSafetyLimit) (*MsgSetSafetyLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSafetyLimit not implemented")
}
func (*UnimplementedMsgServer) SetColdAddress(ctx context.Context, req *MsgSetColdAddress) (*MsgSetColdAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetColdAddress not implemented")
}
func (*UnimplementedMsgServer) SetAutoTransfer(ctx context.Context, req *MsgSetAutoTransfer) (*MsgSetAutoTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAutoTransfer not implemented")
}
func (*UnimplementedMsgServer) AddPartner(ctx context.Context, req *MsgAddPartner) (*MsgAddPartnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPartner not implemented")
}
func (*UnimplementedMsgServer) RemovePartner(ctx context.Context, req *MsgRemovePartner) (*MsgRemovePartnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePartner not implemented")
}
func (*UnimplementedMsgServer) UpdatePartner(ctx context.Context, req *MsgUpdatePartner) (*MsgUpdatePartnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePartner not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetSafetyLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetSafetyLimit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetSafetyLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/natchain.wallet.v1.Msg/SetSafetyLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetSafetyLimit(ctx, req.(*MsgSetSafetyLimit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetColdAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetColdAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetColdAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/natchain.wallet.v1.Msg/SetColdAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetColdAddress(ctx, req.(*MsgSetColdAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetAutoTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetAutoTransfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetAutoTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/natchain.wallet.v1.Msg/SetAutoTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetAutoTransfer(ctx, req.(*MsgSetAutoTransfer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddPartner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddPartner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddPartner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/natchain.wallet.v1.Msg/AddPartner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddPartner(ctx, req.(*MsgAddPartner))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemovePartner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemovePartner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemovePartner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/natchain.wallet.v1.Msg/RemovePartner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemovePartner(ctx, req.(*MsgRemovePartner))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdatePartner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePartner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePartner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/natchain.wallet.v1.Msg/UpdatePartner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePartner(ctx, req.(*MsgUpdatePartner))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "natchain.wallet.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetSafetyLimit",
			Handler:    _Msg_SetSafetyLimit_Handler,
		},
		{
			MethodName: "SetColdAddress",
			Handler:    _Msg_SetColdAddress_Handler,
		},
		{
			MethodName: "SetAutoTransfer",
			Handler:    _Msg_SetAutoTransfer_Handler,
		},
		{
			MethodName: "AddPartner",
			Handler:    _Msg_AddPartner_Handler,
		},
		{
			MethodName: "RemovePartner",
			Handler:    _Msg_RemovePartner_Handler,
		},
		{
			MethodName: "UpdatePartner",
			Handler:    _Msg_UpdatePartner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "natchain/wallet/v1/tx.proto",
}

func (m *MsgSetSafetyLimit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetSafetyLimit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetSafetyLimit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SafetyLimit != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SafetyLimit))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetSafetyLimitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetSafetyLimitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetSafetyLimitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetColdAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetColdAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetColdAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ColdAddress) > 0 {
		i -= len(m.ColdAddress)
		copy(dAtA[i:], m.ColdAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ColdAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetColdAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetColdAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetColdAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetAutoTransfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetAutoTransfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetAutoTransfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Threshold != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Threshold))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetAutoTransferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetAutoTransferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetAutoTransferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddPartner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddPartner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddPartner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddPartnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddPartnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddPartnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRemovePartner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemovePartner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemovePartner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemovePartnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemovePartnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemovePartnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePartner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePartner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePartner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePartnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePartnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePartnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetSafetyLimit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SafetyLimit != 0 {
		n += 1 + sovTx(uint64(m.SafetyLimit))
	}
	return n
}

func (m *MsgSetSafetyLimitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetColdAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ColdAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetColdAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetAutoTransfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Threshold != 0 {
		n += 1 + sovTx(uint64(m.Threshold))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	return n
}

func (m *MsgSetAutoTransferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddPartner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddPartnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRemovePartner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRemovePartnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdatePartner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdatePartnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetSafetyLimit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetSafetyLimit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetSafetyLimit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SafetyLimit", wireType)
			}
			m.SafetyLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SafetyLimit |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetSafetyLimitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetSafetyLimitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetSafetyLimitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetColdAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetColdAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetColdAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ColdAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ColdAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetColdAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetColdAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetColdAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetAutoTransfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetAutoTransfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetAutoTransfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threshold", wireType)
			}
			m.Threshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Threshold |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetAutoTransferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetAutoTransferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetAutoTransferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddPartner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddPartner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddPartner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddPartnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddPartnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddPartnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemovePartner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemovePartner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemovePartner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemovePartnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemovePartnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemovePartnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePartner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePartner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePartner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePartnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePartnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePartnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
