// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: natchain/merchant/v1/merchant.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Merchant 商家信息
type Merchant struct {
	Address        string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ApiKey         string `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	CallbackUrl    string `protobuf:"bytes,4,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	CreatedAt      int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CommissionRate int64  `protobuf:"varint,6,opt,name=commission_rate,json=commissionRate,proto3" json:"commission_rate,omitempty"`
	Active         bool   `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *Merchant) Reset()         { *m = Merchant{} }
func (m *Merchant) String() string { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()    {}
func (*Merchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e04c514bb288c96, []int{0}
}
func (m *Merchant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Merchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Merchant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Merchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchant.Merge(m, src)
}
func (m *Merchant) XXX_Size() int {
	return m.Size()
}
func (m *Merchant) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchant.DiscardUnknown(m)
}

var xxx_messageInfo_Merchant proto.InternalMessageInfo

func (m *Merchant) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Merchant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Merchant) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *Merchant) GetCallbackUrl() string {
	if m != nil {
		return m.CallbackUrl
	}
	return ""
}

func (m *Merchant) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Merchant) GetCommissionRate() int64 {
	if m != nil {
		return m.CommissionRate
	}
	return 0
}

func (m *Merchant) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

// PaymentRecord 支付记录
type PaymentRecord struct {
	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantAddress string `protobuf:"bytes,2,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
	UserAddress     string `protobuf:"bytes,3,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	Amount          string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status          string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp       int64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CallbackData    string `protobuf:"bytes,7,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"`
}

func (m *PaymentRecord) Reset()         { *m = PaymentRecord{} }
func (m *PaymentRecord) String() string { return proto.CompactTextString(m) }
func (*PaymentRecord) ProtoMessage()    {}
func (*PaymentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e04c514bb288c96, []int{1}
}
func (m *PaymentRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PaymentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PaymentRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PaymentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRecord.Merge(m, src)
}
func (m *PaymentRecord) XXX_Size() int {
	return m.Size()
}
func (m *PaymentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRecord proto.InternalMessageInfo

func (m *PaymentRecord) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentRecord) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

func (m *PaymentRecord) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *PaymentRecord) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *PaymentRecord) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PaymentRecord) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PaymentRecord) GetCallbackData() string {
	if m != nil {
		return m.CallbackData
	}
	return ""
}

func init() {
	proto.RegisterType((*Merchant)(nil), "natchain.merchant.v1.Merchant")
	proto.RegisterType((*PaymentRecord)(nil), "natchain.merchant.v1.PaymentRecord")
}

func init() {
	proto.RegisterFile("natchain/merchant/v1/merchant.proto", fileDescriptor_3e04c514bb288c96)
}

var fileDescriptor_3e04c514bb288c96 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x92, 0xcf, 0x8a, 0xdb, 0x30,
	0x10, 0xc6, 0xa3, 0xec, 0xd6, 0x59, 0xcf, 0xfe, 0x2b, 0xa2, 0xb4, 0x2a, 0xb4, 0x26, 0xbb, 0x7b,
	0x68, 0x7a, 0xd9, 0x10, 0xf2, 0x04, 0x29, 0xbd, 0x95, 0x42, 0x31, 0xf4, 0xd2, 0x8b, 0x99, 0xc8,
	0x82, 0x88, 0x58, 0xb6, 0x91, 0xc6, 0xa1, 0x7e, 0x8b, 0x3e, 0x56, 0x8f, 0x39, 0xf4, 0xd0, 0x63,
	0x48, 0x5e, 0x64, 0x89, 0x22, 0x3b, 0x37, 0x7d, 0xbf, 0xf9, 0x0e, 0xfa, 0x0d, 0x03, 0x4f, 0x25,
	0x92, 0x5c, 0xa1, 0x2e, 0xa7, 0x46, 0x59, 0xb9, 0xc2, 0x92, 0xa6, 0x9b, 0x59, 0xff, 0x7e, 0xae,
	0x6d, 0x45, 0x15, 0x7f, 0xd3, 0x95, 0x9e, 0xfb, 0xc1, 0x66, 0xf6, 0xf8, 0x8f, 0xc1, 0xd5, 0xf7,
	0x90, 0xb9, 0x80, 0x11, 0xe6, 0xb9, 0x55, 0xce, 0x09, 0x36, 0x66, 0x93, 0x38, 0xed, 0x22, 0xe7,
	0x70, 0x59, 0xa2, 0x51, 0x62, 0xe8, 0xb1, 0x7f, 0xf3, 0x77, 0x30, 0xc2, 0x5a, 0x67, 0x6b, 0xd5,
	0x8a, 0x0b, 0x8f, 0x23, 0xac, 0xf5, 0x37, 0xd5, 0xf2, 0x07, 0xb8, 0x91, 0x58, 0x14, 0x4b, 0x94,
	0xeb, 0xac, 0xb1, 0x85, 0xb8, 0xf4, 0xd3, 0xeb, 0x8e, 0xfd, 0xb4, 0x05, 0xff, 0x08, 0x20, 0xad,
	0x42, 0x52, 0x79, 0x86, 0x24, 0x5e, 0x8d, 0xd9, 0xe4, 0x22, 0x8d, 0x03, 0x59, 0x10, 0xff, 0x04,
	0xf7, 0xb2, 0x32, 0x46, 0x3b, 0xa7, 0xab, 0x32, 0xb3, 0x48, 0x4a, 0x44, 0xbe, 0x73, 0x77, 0xc6,
	0x29, 0x92, 0xe2, 0x6f, 0x21, 0x42, 0x49, 0x7a, 0xa3, 0xc4, 0x68, 0xcc, 0x26, 0x57, 0x69, 0x48,
	0x8f, 0x3b, 0x06, 0xb7, 0x3f, 0xb0, 0x35, 0xaa, 0xa4, 0x54, 0xc9, 0xca, 0xe6, 0xfc, 0x0e, 0x86,
	0x3a, 0x0f, 0x5a, 0x43, 0x9d, 0xf3, 0xcf, 0xf0, 0xba, 0xdb, 0x43, 0xd6, 0x49, 0x9f, 0xec, 0xee,
	0x3b, 0xbe, 0x08, 0xf2, 0x0f, 0x70, 0xd3, 0x38, 0x65, 0xfb, 0xda, 0xc9, 0xf6, 0xfa, 0xc8, 0xba,
	0xca, 0xf1, 0x1f, 0xa6, 0x6a, 0x4a, 0x0a, 0xb2, 0x21, 0x1d, 0xb9, 0x23, 0xa4, 0xc6, 0x79, 0xc7,
	0x38, 0x0d, 0x89, 0x7f, 0x80, 0x98, 0xb4, 0x51, 0x8e, 0xd0, 0xd4, 0x41, 0xed, 0x0c, 0xf8, 0x13,
	0xdc, 0xf6, 0x0b, 0xcc, 0x91, 0xd0, 0xcb, 0xc5, 0x69, 0xbf, 0xd5, 0xaf, 0x48, 0xf8, 0x65, 0xfe,
	0x77, 0x9f, 0xb0, 0xed, 0x3e, 0x61, 0xbb, 0x7d, 0xc2, 0xfe, 0x1c, 0x92, 0xc1, 0xf6, 0x90, 0x0c,
	0xfe, 0x1f, 0x92, 0xc1, 0xaf, 0xf7, 0xfd, 0x39, 0xfc, 0x3e, 0x1f, 0x04, 0xb5, 0xb5, 0x72, 0xcb,
	0xc8, 0xdf, 0xc2, 0xfc, 0x25, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x11, 0xfc, 0xe0, 0x32, 0x02, 0x00,
	0x00,
}

func (m *Merchant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Merchant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Merchant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.CommissionRate != 0 {
		i = encodeVarintMerchant(dAtA, i, uint64(m.CommissionRate))
		i--
		dAtA[i] = 0x30
	}
	if m.CreatedAt != 0 {
		i = encodeVarintMerchant(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x28
	}
	if len(m.CallbackUrl) > 0 {
		i -= len(m.CallbackUrl)
		copy(dAtA[i:], m.CallbackUrl)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.CallbackUrl)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ApiKey) > 0 {
		i -= len(m.ApiKey)
		copy(dAtA[i:], m.ApiKey)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.ApiKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PaymentRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PaymentRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CallbackData) > 0 {
		i -= len(m.CallbackData)
		copy(dAtA[i:], m.CallbackData)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.CallbackData)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Timestamp != 0 {
		i = encodeVarintMerchant(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.UserAddress) > 0 {
		i -= len(m.UserAddress)
		copy(dAtA[i:], m.UserAddress)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.UserAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MerchantAddress) > 0 {
		i -= len(m.MerchantAddress)
		copy(dAtA[i:], m.MerchantAddress)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.MerchantAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMerchant(dAtA []byte, offset int, v uint64) int {
	offset -= sovMerchant(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Merchant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.ApiKey)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.CallbackUrl)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovMerchant(uint64(m.CreatedAt))
	}
	if m.CommissionRate != 0 {
		n += 1 + sovMerchant(uint64(m.CommissionRate))
	}
	if m.Active {
		n += 2
	}
	return n
}

func (m *PaymentRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.MerchantAddress)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.UserAddress)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovMerchant(uint64(m.Timestamp))
	}
	l = len(m.CallbackData)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	return n
}

func sovMerchant(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMerchant(x uint64) (n int) {
	return sovMerchant(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Merchant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMerchant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Merchant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Merchant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApiKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissionRate", wireType)
			}
			m.CommissionRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommissionRate |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipMerchant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMerchant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PaymentRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMerchant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PaymentRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PaymentRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMerchant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMerchant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMerchant(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMerchant
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMerchant
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMerchant
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMerchant
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMerchant        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMerchant          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMerchant = fmt.Errorf("proto: unexpected end of group")
)
