// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: natchain/merchant/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterMerchant struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CallbackUrl    string `protobuf:"bytes,3,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	CommissionRate int64  `protobuf:"varint,4,opt,name=commission_rate,json=commissionRate,proto3" json:"commission_rate,omitempty"`
}

func (m *MsgRegisterMerchant) Reset()         { *m = MsgRegisterMerchant{} }
func (m *MsgRegisterMerchant) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterMerchant) ProtoMessage()    {}
func (*MsgRegisterMerchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7a44d939dbf4b4, []int{0}
}
func (m *MsgRegisterMerchant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterMerchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterMerchant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterMerchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterMerchant.Merge(m, src)
}
func (m *MsgRegisterMerchant) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterMerchant) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterMerchant.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterMerchant proto.InternalMessageInfo

func (m *MsgRegisterMerchant) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterMerchant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgRegisterMerchant) GetCallbackUrl() string {
	if m != nil {
		return m.CallbackUrl
	}
	return ""
}

func (m *MsgRegisterMerchant) GetCommissionRate() int64 {
	if m != nil {
		return m.CommissionRate
	}
	return 0
}

type MsgRegisterMerchantResponse struct {
	ApiKey string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
}

func (m *MsgRegisterMerchantResponse) Reset()         { *m = MsgRegisterMerchantResponse{} }
func (m *MsgRegisterMerchantResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterMerchantResponse) ProtoMessage()    {}
func (*MsgRegisterMerchantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7a44d939dbf4b4, []int{1}
}
func (m *MsgRegisterMerchantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterMerchantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterMerchantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterMerchantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterMerchantResponse.Merge(m, src)
}
func (m *MsgRegisterMerchantResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterMerchantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterMerchantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterMerchantResponse proto.InternalMessageInfo

func (m *MsgRegisterMerchantResponse) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

type MsgUpdateMerchant struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CallbackUrl    string `protobuf:"bytes,3,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	CommissionRate int64  `protobuf:"varint,4,opt,name=commission_rate,json=commissionRate,proto3" json:"commission_rate,omitempty"`
}

func (m *MsgUpdateMerchant) Reset()         { *m = MsgUpdateMerchant{} }
func (m *MsgUpdateMerchant) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateMerchant) ProtoMessage()    {}
func (*MsgUpdateMerchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7a44d939dbf4b4, []int{2}
}
func (m *MsgUpdateMerchant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateMerchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateMerchant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateMerchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateMerchant.Merge(m, src)
}
func (m *MsgUpdateMerchant) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateMerchant) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateMerchant.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateMerchant proto.InternalMessageInfo

func (m *MsgUpdateMerchant) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateMerchant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgUpdateMerchant) GetCallbackUrl() string {
	if m != nil {
		return m.CallbackUrl
	}
	return ""
}

func (m *MsgUpdateMerchant) GetCommissionRate() int64 {
	if m != nil {
		return m.CommissionRate
	}
	return 0
}

type MsgUpdateMerchantResponse struct {
}

func (m *MsgUpdateMerchantResponse) Reset()         { *m = MsgUpdateMerchantResponse{} }
func (m *MsgUpdateMerchantResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateMerchantResponse) ProtoMessage()    {}
func (*MsgUpdateMerchantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7a44d939dbf4b4, []int{3}
}
func (m *MsgUpdateMerchantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateMerchantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateMerchantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateMerchantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateMerchantResponse.Merge(m, src)
}
func (m *MsgUpdateMerchantResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateMerchantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateMerchantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateMerchantResponse proto.InternalMessageInfo

type MsgRegenerateApiKey struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgRegenerateApiKey) Reset()         { *m = MsgRegenerateApiKey{} }
func (m *MsgRegenerateApiKey) String() string { return proto.CompactTextString(m) }
func (*MsgRegenerateApiKey) ProtoMessage()    {}
func (*MsgRegenerateApiKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7a44d939dbf4b4, []int{4}
}
func (m *MsgRegenerateApiKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegenerateApiKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegenerateApiKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegenerateApiKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegenerateApiKey.Merge(m, src)
}
func (m *MsgRegenerateApiKey) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegenerateApiKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegenerateApiKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegenerateApiKey proto.InternalMessageInfo

func (m *MsgRegenerateApiKey) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgRegenerateApiKeyResponse struct {
	ApiKey string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
}

func (m *MsgRegenerateApiKeyResponse) Reset()         { *m = MsgRegenerateApiKeyResponse{} }
func (m *MsgRegenerateApiKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegenerateApiKeyResponse) ProtoMessage()    {}
func (*MsgRegenerateApiKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7a44d939dbf4b4, []int{5}
}
func (m *MsgRegenerateApiKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegenerateApiKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegenerateApiKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegenerateApiKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegenerateApiKeyResponse.Merge(m, src)
}
func (m *MsgRegenerateApiKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegenerateApiKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegenerateApiKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegenerateApiKeyResponse proto.InternalMessageInfo

func (m *MsgRegenerateApiKeyResponse) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

type MsgCreatePayment struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	MerchantAddress string `protobuf:"bytes,2,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
	Amount          string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CallbackData    string `protobuf:"bytes,4,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"`
}

func (m *MsgCreatePayment) Reset()         { *m = MsgCreatePayment{} }
func (m *MsgCreatePayment) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePayment) ProtoMessage()    {}
func (*MsgCreatePayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7a44d939dbf4b4, []int{6}
}
func (m *MsgCreatePayment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePayment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePayment.Merge(m, src)
}
func (m *MsgCreatePayment) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePayment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePayment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePayment proto.InternalMessageInfo

func (m *MsgCreatePayment) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreatePayment) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

func (m *MsgCreatePayment) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgCreatePayment) GetCallbackData() string {
	if m != nil {
		return m.CallbackData
	}
	return ""
}

type MsgCreatePaymentResponse struct {
	PaymentId string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
}

func (m *MsgCreatePaymentResponse) Reset()         { *m = MsgCreatePaymentResponse{} }
func (m *MsgCreatePaymentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePaymentResponse) ProtoMessage()    {}
func (*MsgCreatePaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7a44d939dbf4b4, []int{7}
}
func (m *MsgCreatePaymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePaymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePaymentResponse.Merge(m, src)
}
func (m *MsgCreatePaymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePaymentResponse proto.InternalMessageInfo

func (m *MsgCreatePaymentResponse) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

type MsgConfirmPayment struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PaymentId string `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status    string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *MsgConfirmPayment) Reset()         { *m = MsgConfirmPayment{} }
func (m *MsgConfirmPayment) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmPayment) ProtoMessage()    {}
func (*MsgConfirmPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7a44d939dbf4b4, []int{8}
}
func (m *MsgConfirmPayment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmPayment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmPayment.Merge(m, src)
}
func (m *MsgConfirmPayment) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmPayment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmPayment proto.InternalMessageInfo

func (m *MsgConfirmPayment) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgConfirmPayment) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func (m *MsgConfirmPayment) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MsgConfirmPaymentResponse struct {
}

func (m *MsgConfirmPaymentResponse) Reset()         { *m = MsgConfirmPaymentResponse{} }
func (m *MsgConfirmPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmPaymentResponse) ProtoMessage()    {}
func (*MsgConfirmPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7a44d939dbf4b4, []int{9}
}
func (m *MsgConfirmPaymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmPaymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmPaymentResponse.Merge(m, src)
}
func (m *MsgConfirmPaymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmPaymentResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterMerchant)(nil), "natchain.merchant.v1.MsgRegisterMerchant")
	proto.RegisterType((*MsgRegisterMerchantResponse)(nil), "natchain.merchant.v1.MsgRegisterMerchantResponse")
	proto.RegisterType((*MsgUpdateMerchant)(nil), "natchain.merchant.v1.MsgUpdateMerchant")
	proto.RegisterType((*MsgUpdateMerchantResponse)(nil), "natchain.merchant.v1.MsgUpdateMerchantResponse")
	proto.RegisterType((*MsgRegenerateApiKey)(nil), "natchain.merchant.v1.MsgRegenerateApiKey")
	proto.RegisterType((*MsgRegenerateApiKeyResponse)(nil), "natchain.merchant.v1.MsgRegenerateApiKeyResponse")
	proto.RegisterType((*MsgCreatePayment)(nil), "natchain.merchant.v1.MsgCreatePayment")
	proto.RegisterType((*MsgCreatePaymentResponse)(nil), "natchain.merchant.v1.MsgCreatePaymentResponse")
	proto.RegisterType((*MsgConfirmPayment)(nil), "natchain.merchant.v1.MsgConfirmPayment")
	proto.RegisterType((*MsgConfirmPaymentResponse)(nil), "natchain.merchant.v1.MsgConfirmPaymentResponse")
}

func init() { proto.RegisterFile("natchain/merchant/v1/tx.proto", fileDescriptor_8b7a44d939dbf4b4) }

var fileDescriptor_8b7a44d939dbf4b4 = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x8d, 0x9b, 0x90, 0x2a, 0x97, 0x3e, 0x82, 0xa9, 0xa8, 0xeb, 0xaa, 0x56, 0x09, 0x12, 0x7d,
	0x2c, 0x6c, 0x85, 0x4a, 0x48, 0x20, 0xb1, 0x28, 0x65, 0x83, 0x50, 0x24, 0x64, 0xa9, 0x1b, 0x36,
	0xd1, 0xad, 0x3d, 0xb8, 0xa6, 0x19, 0x8f, 0x35, 0x33, 0xa9, 0x9a, 0x1d, 0xe2, 0x0b, 0xd8, 0x23,
	0x36, 0x7c, 0x41, 0xf9, 0x0b, 0x96, 0x5d, 0xb2, 0x44, 0xc9, 0xa2, 0xbf, 0x81, 0x62, 0x7b, 0x5c,
	0x9c, 0x3a, 0x69, 0x96, 0xec, 0x66, 0xce, 0x9c, 0xdc, 0xb9, 0xe7, 0xf8, 0xdc, 0x0c, 0x6c, 0x45,
	0x28, 0xbd, 0x53, 0x0c, 0x23, 0x87, 0x12, 0xee, 0x9d, 0x62, 0x24, 0x9d, 0xf3, 0xb6, 0x23, 0x2f,
	0xec, 0x98, 0x33, 0xc9, 0xf4, 0x35, 0x75, 0x6c, 0xab, 0x63, 0xfb, 0xbc, 0x6d, 0xae, 0x7b, 0x4c,
	0x50, 0x26, 0x1c, 0x2a, 0x82, 0x31, 0x9b, 0x8a, 0x20, 0xa5, 0x9b, 0x6b, 0x01, 0x0b, 0x58, 0xb2,
	0x74, 0xc6, 0xab, 0x14, 0x6d, 0x7d, 0xd7, 0xe0, 0x61, 0x47, 0x04, 0x2e, 0x09, 0x42, 0x21, 0x09,
	0xef, 0x64, 0x95, 0x74, 0x03, 0x16, 0x3d, 0x4e, 0x50, 0x32, 0x6e, 0x68, 0xdb, 0xda, 0x6e, 0xc3,
	0x55, 0x5b, 0x5d, 0x87, 0x5a, 0x84, 0x94, 0x18, 0x0b, 0x09, 0x9c, 0xac, 0xf5, 0xc7, 0xb0, 0xe4,
	0x61, 0xaf, 0x77, 0x82, 0xde, 0x59, 0xb7, 0xcf, 0x7b, 0x46, 0x35, 0x39, 0xbb, 0xaf, 0xb0, 0x63,
	0xde, 0xd3, 0x77, 0x60, 0xd5, 0x63, 0x94, 0x86, 0x42, 0x84, 0x2c, 0xea, 0x72, 0x94, 0xc4, 0xa8,
	0x6d, 0x6b, 0xbb, 0x55, 0x77, 0xe5, 0x06, 0x76, 0x51, 0x92, 0x97, 0x4b, 0x5f, 0xae, 0x2f, 0xf7,
	0xd5, 0x6d, 0xad, 0xe7, 0xb0, 0x59, 0xd2, 0x9e, 0x4b, 0x44, 0xcc, 0x22, 0x41, 0xf4, 0x75, 0x58,
	0xc4, 0x38, 0xec, 0x9e, 0x91, 0x41, 0xd6, 0x66, 0x1d, 0xe3, 0xf0, 0x1d, 0x19, 0xb4, 0xbe, 0x69,
	0xf0, 0xa0, 0x23, 0x82, 0xe3, 0xd8, 0x47, 0x49, 0xfe, 0x3b, 0x55, 0x9b, 0xb0, 0x71, 0xab, 0x39,
	0xa5, 0xa9, 0xf5, 0x4a, 0x7d, 0x11, 0x12, 0x91, 0x71, 0xc5, 0xc3, 0x44, 0xd1, 0xf4, 0xde, 0xa7,
	0x39, 0x56, 0xf8, 0xf9, 0xdd, 0x8e, 0xfd, 0xd0, 0xa0, 0xd9, 0x11, 0xc1, 0xd1, 0xb8, 0x0c, 0x79,
	0x8f, 0x03, 0x4a, 0x66, 0x1a, 0xb6, 0x07, 0x4d, 0x15, 0xbb, 0x2e, 0xfa, 0x3e, 0x27, 0x42, 0x64,
	0xe6, 0xad, 0x2a, 0xfc, 0x30, 0x85, 0xf5, 0x47, 0x50, 0x47, 0xca, 0xfa, 0x91, 0xcc, 0x1c, 0xcc,
	0x76, 0xfa, 0x13, 0x58, 0xce, 0xfd, 0xf5, 0x51, 0x62, 0x62, 0x5d, 0xc3, 0xcd, 0x4d, 0x7f, 0x83,
	0x12, 0x27, 0xc4, 0xbd, 0x00, 0x63, 0xb2, 0xc7, 0x5c, 0xd9, 0x16, 0x40, 0x9c, 0x42, 0xdd, 0xd0,
	0xcf, 0xda, 0x6d, 0x64, 0xc8, 0x5b, 0xbf, 0xc5, 0x93, 0x40, 0x1c, 0xb1, 0xe8, 0x63, 0xc8, 0xe9,
	0xdd, 0xfa, 0x8a, 0xd5, 0x16, 0x26, 0xaa, 0x8d, 0x35, 0x09, 0x89, 0xb2, 0x2f, 0x94, 0xa6, 0x74,
	0x57, 0xfa, 0x9d, 0x8b, 0x77, 0xaa, 0x7e, 0x9f, 0xfd, 0xac, 0x41, 0xb5, 0x23, 0x02, 0x3d, 0x86,
	0xe6, 0xad, 0xf1, 0xdb, 0xb3, 0xcb, 0x86, 0xdb, 0x2e, 0x19, 0x05, 0xb3, 0x3d, 0x37, 0x35, 0x77,
	0xea, 0x13, 0xac, 0x4c, 0x0c, 0xc6, 0xce, 0xd4, 0x22, 0x45, 0xa2, 0xe9, 0xcc, 0x49, 0xcc, 0xef,
	0x4a, 0xd5, 0x15, 0xa3, 0x3c, 0x53, 0x5d, 0x81, 0x3a, 0x5b, 0x5d, 0x79, 0xc2, 0x03, 0x58, 0x2e,
	0x86, 0xf8, 0xe9, 0xd4, 0x1a, 0x05, 0x9e, 0x69, 0xcf, 0xc7, 0xfb, 0xd7, 0xc6, 0x89, 0x38, 0x4d,
	0xb7, 0xb1, 0x48, 0x9c, 0x61, 0x63, 0x79, 0x58, 0xcc, 0x7b, 0x9f, 0xaf, 0x2f, 0xf7, 0xb5, 0xd7,
	0x07, 0xbf, 0x86, 0x96, 0x76, 0x35, 0xb4, 0xb4, 0x3f, 0x43, 0x4b, 0xfb, 0x3a, 0xb2, 0x2a, 0x57,
	0x23, 0xab, 0xf2, 0x7b, 0x64, 0x55, 0x3e, 0x6c, 0xe4, 0x8f, 0xc5, 0xc5, 0xcd, 0x73, 0x21, 0x07,
	0x31, 0x11, 0x27, 0xf5, 0xe4, 0xaf, 0xfe, 0xe0, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x84,
	0x94, 0xfc, 0x50, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// 注册商家
	RegisterMerchant(ctx context.Context, in *MsgRegisterMerchant, opts ...grpc.CallOption) (*MsgRegisterMerchantResponse, error)
	// 更新商家信息
	UpdateMerchant(ctx context.Context, in *MsgUpdateMerchant, opts ...grpc.CallOption) (*MsgUpdateMerchantResponse, error)
	// 生成新API Key
	RegenerateApiKey(ctx context.Context, in *MsgRegenerateApiKey, opts ...grpc.CallOption) (*MsgRegenerateApiKeyResponse, error)
	// 创建支付
	CreatePayment(ctx context.Context, in *MsgCreatePayment, opts ...grpc.CallOption) (*MsgCreatePaymentResponse, error)
	// 确认支付
	ConfirmPayment(ctx context.Context, in *MsgConfirmPayment, opts ...grpc.CallOption) (*MsgConfirmPaymentResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterMerchant(ctx context.Context, in *MsgRegisterMerchant, opts ...grpc.CallOption) (*MsgRegisterMerchantResponse, error) {
	out := new(MsgRegisterMerchantResponse)
	err := c.cc.Invoke(ctx, "/natchain.merchant.v1.Msg/RegisterMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateMerchant(ctx context.Context, in *MsgUpdateMerchant, opts ...grpc.CallOption) (*MsgUpdateMerchantResponse, error) {
	out := new(MsgUpdateMerchantResponse)
	err := c.cc.Invoke(ctx, "/natchain.merchant.v1.Msg/UpdateMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegenerateApiKey(ctx context.Context, in *MsgRegenerateApiKey, opts ...grpc.CallOption) (*MsgRegenerateApiKeyResponse, error) {
	out := new(MsgRegenerateApiKeyResponse)
	err := c.cc.Invoke(ctx, "/natchain.merchant.v1.Msg/RegenerateApiKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreatePayment(ctx context.Context, in *MsgCreatePayment, opts ...grpc.CallOption) (*MsgCreatePaymentResponse, error) {
	out := new(MsgCreatePaymentResponse)
	err := c.cc.Invoke(ctx, "/natchain.merchant.v1.Msg/CreatePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ConfirmPayment(ctx context.Context, in *MsgConfirmPayment, opts ...grpc.CallOption) (*MsgConfirmPaymentResponse, error) {
	out := new(MsgConfirmPaymentResponse)
	err := c.cc.Invoke(ctx, "/natchain.merchant.v1.Msg/ConfirmPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// 注册商家
	RegisterMerchant(context.Context, *MsgRegisterMerchant) (*MsgRegisterMerchantResponse, error)
	// 更新商家信息
	UpdateMerchant(context.Context, *MsgUpdateMerchant) (*MsgUpdateMerchantResponse, error)
	// 生成新API Key
	RegenerateApiKey(context.Context, *MsgRegenerateApiKey) (*MsgRegenerateApiKeyResponse, error)
	// 创建支付
	CreatePayment(context.Context, *MsgCreatePayment) (*MsgCreatePaymentResponse, error)
	// 确认支付
	ConfirmPayment(context.Context, *MsgConfirmPayment) (*MsgConfirmPaymentResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterMerchant(ctx context.Context, req *MsgRegisterMerchant) (*MsgRegisterMerchantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterMerchant not implemented")
}
func (*UnimplementedMsgServer) UpdateMerchant(ctx context.Context, req *MsgUpdateMerchant) (*MsgUpdateMerchantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMerchant not implemented")
}
func (*UnimplementedMsgServer) RegenerateApiKey(ctx context.Context, req *MsgRegenerateApiKey) (*MsgRegenerateApiKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegenerateApiKey not implemented")
}
func (*UnimplementedMsgServer) CreatePayment(ctx context.Context, req *MsgCreatePayment) (*MsgCreatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePayment not implemented")
}
func (*UnimplementedMsgServer) ConfirmPayment(ctx context.Context, req *MsgConfirmPayment) (*MsgConfirmPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPayment not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/natchain.merchant.v1.Msg/RegisterMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterMerchant(ctx, req.(*MsgRegisterMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/natchain.merchant.v1.Msg/UpdateMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateMerchant(ctx, req.(*MsgUpdateMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegenerateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegenerateApiKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegenerateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/natchain.merchant.v1.Msg/RegenerateApiKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegenerateApiKey(ctx, req.(*MsgRegenerateApiKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePayment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/natchain.merchant.v1.Msg/CreatePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePayment(ctx, req.(*MsgCreatePayment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfirmPayment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/natchain.merchant.v1.Msg/ConfirmPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConfirmPayment(ctx, req.(*MsgConfirmPayment))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "natchain.merchant.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterMerchant",
			Handler:    _Msg_RegisterMerchant_Handler,
		},
		{
			MethodName: "UpdateMerchant",
			Handler:    _Msg_UpdateMerchant_Handler,
		},
		{
			MethodName: "RegenerateApiKey",
			Handler:    _Msg_RegenerateApiKey_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _Msg_CreatePayment_Handler,
		},
		{
			MethodName: "ConfirmPayment",
			Handler:    _Msg_ConfirmPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "natchain/merchant/v1/tx.proto",
}

func (m *MsgRegisterMerchant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterMerchant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterMerchant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CommissionRate != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CommissionRate))
		i--
		dAtA[i] = 0x20
	}
	if len(m.CallbackUrl) > 0 {
		i -= len(m.CallbackUrl)
		copy(dAtA[i:], m.CallbackUrl)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CallbackUrl)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterMerchantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterMerchantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterMerchantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ApiKey) > 0 {
		i -= len(m.ApiKey)
		copy(dAtA[i:], m.ApiKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ApiKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateMerchant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateMerchant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateMerchant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CommissionRate != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CommissionRate))
		i--
		dAtA[i] = 0x20
	}
	if len(m.CallbackUrl) > 0 {
		i -= len(m.CallbackUrl)
		copy(dAtA[i:], m.CallbackUrl)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CallbackUrl)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateMerchantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateMerchantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateMerchantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegenerateApiKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegenerateApiKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegenerateApiKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegenerateApiKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegenerateApiKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegenerateApiKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ApiKey) > 0 {
		i -= len(m.ApiKey)
		copy(dAtA[i:], m.ApiKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ApiKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePayment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePayment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePayment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CallbackData) > 0 {
		i -= len(m.CallbackData)
		copy(dAtA[i:], m.CallbackData)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CallbackData)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MerchantAddress) > 0 {
		i -= len(m.MerchantAddress)
		copy(dAtA[i:], m.MerchantAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MerchantAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePaymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePaymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePaymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PaymentId) > 0 {
		i -= len(m.PaymentId)
		copy(dAtA[i:], m.PaymentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PaymentId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConfirmPayment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmPayment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmPayment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PaymentId) > 0 {
		i -= len(m.PaymentId)
		copy(dAtA[i:], m.PaymentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PaymentId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConfirmPaymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmPaymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmPaymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterMerchant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CallbackUrl)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.CommissionRate != 0 {
		n += 1 + sovTx(uint64(m.CommissionRate))
	}
	return n
}

func (m *MsgRegisterMerchantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ApiKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateMerchant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CallbackUrl)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.CommissionRate != 0 {
		n += 1 + sovTx(uint64(m.CommissionRate))
	}
	return n
}

func (m *MsgUpdateMerchantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegenerateApiKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegenerateApiKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ApiKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreatePayment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MerchantAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CallbackData)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreatePaymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PaymentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgConfirmPayment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PaymentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgConfirmPaymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterMerchant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterMerchant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterMerchant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissionRate", wireType)
			}
			m.CommissionRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommissionRate |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterMerchantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterMerchantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterMerchantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApiKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateMerchant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateMerchant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateMerchant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissionRate", wireType)
			}
			m.CommissionRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommissionRate |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateMerchantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateMerchantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateMerchantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegenerateApiKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegenerateApiKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegenerateApiKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegenerateApiKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegenerateApiKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegenerateApiKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApiKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePayment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePayment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePayment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePaymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePaymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePaymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfirmPayment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmPayment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmPayment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfirmPaymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmPaymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmPaymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
